// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(function() {
    var Todo, TodoList, Todos;
    Todo = (function(_super) {
      __extends(Todo, _super);

      function Todo() {
        return Todo.__super__.constructor.apply(this, arguments);
      }

      Todo.prototype.defaults = function() {
        return {
          title: "empty todo...",
          order: Todos.nextOrder(),
          done: false
        };
      };

      Todo.prototype.toggle = function() {
        return this.save({
          done: !this.get("done")
        });
      };

      return Todo;

    })(Backbone.Model);
    TodoList = (function(_super) {
      __extends(TodoList, _super);

      function TodoList() {
        return TodoList.__super__.constructor.apply(this, arguments);
      }

      TodoList.prototype.model = Todo;

      TodoList.prototype.localStorage = new Backbone.LocalStorage('todos-backbone');

      TodoList.prototype.done = function() {
        return this.where({
          done: true
        });
      };

      TodoList.prototype.remaining = function() {
        return this.where({
          done: true
        });
      };

      TodoList.prototype.nextOrder = function() {
        if (!this.length) {
          return 1;
        }
        return this.last().get('order') + 1;
      };

      TodoList.prototype.comparator = 'order';

      return TodoList;

    })(Backbone.Collection);
    return Todos = new TodoList;
  });

}).call(this);
